/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelCapability } from './ModelCapability';
import {
    ModelCapabilityFromJSON,
    ModelCapabilityFromJSONTyped,
    ModelCapabilityToJSON,
    ModelCapabilityToJSONTyped,
} from './ModelCapability';
import type { ProviderType } from './ProviderType';
import {
    ProviderTypeFromJSON,
    ProviderTypeFromJSONTyped,
    ProviderTypeToJSON,
    ProviderTypeToJSONTyped,
} from './ProviderType';

/**
 * Model configuration for frontend.
 * @export
 * @interface ConfigModel
 */
export interface ConfigModel {
    /**
     * 
     * @type {string}
     * @memberof ConfigModel
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigModel
     */
    model: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigModel
     */
    maxContextSize: number;
    /**
     * 
     * @type {Set<ModelCapability>}
     * @memberof ConfigModel
     */
    capabilities?: Set<ModelCapability> | null;
    /**
     * Model key in kimi-cli config (Config.models)
     * @type {string}
     * @memberof ConfigModel
     */
    name: string;
    /**
     * Provider type (LLMProvider.type)
     * @type {ProviderType}
     * @memberof ConfigModel
     */
    providerType: ProviderType;
}



/**
 * Check if a given object implements the ConfigModel interface.
 */
export function instanceOfConfigModel(value: object): value is ConfigModel {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('maxContextSize' in value) || value['maxContextSize'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('providerType' in value) || value['providerType'] === undefined) return false;
    return true;
}

export function ConfigModelFromJSON(json: any): ConfigModel {
    return ConfigModelFromJSONTyped(json, false);
}

export function ConfigModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigModel {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'model': json['model'],
        'maxContextSize': json['max_context_size'],
        'capabilities': json['capabilities'] == null ? undefined : (new Set((json['capabilities'] as Array<any>).map(ModelCapabilityFromJSON))),
        'name': json['name'],
        'providerType': ProviderTypeFromJSON(json['provider_type']),
    };
}

export function ConfigModelToJSON(json: any): ConfigModel {
    return ConfigModelToJSONTyped(json, false);
}

export function ConfigModelToJSONTyped(value?: ConfigModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'model': value['model'],
        'max_context_size': value['maxContextSize'],
        'capabilities': value['capabilities'] == null ? undefined : (Array.from(value['capabilities'] as Set<any>).map(ModelCapabilityToJSON)),
        'name': value['name'],
        'provider_type': ProviderTypeToJSON(value['providerType']),
    };
}

