/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Raw config.toml content.
 * @export
 * @interface ConfigToml
 */
export interface ConfigToml {
    /**
     * Raw TOML content
     * @type {string}
     * @memberof ConfigToml
     */
    content: string;
    /**
     * Path to config file
     * @type {string}
     * @memberof ConfigToml
     */
    path: string;
}

/**
 * Check if a given object implements the ConfigToml interface.
 */
export function instanceOfConfigToml(value: object): value is ConfigToml {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function ConfigTomlFromJSON(json: any): ConfigToml {
    return ConfigTomlFromJSONTyped(json, false);
}

export function ConfigTomlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigToml {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'path': json['path'],
    };
}

export function ConfigTomlToJSON(json: any): ConfigToml {
    return ConfigTomlToJSONTyped(json, false);
}

export function ConfigTomlToJSONTyped(value?: ConfigToml | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'path': value['path'],
    };
}

