/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Generate title response.
 * @export
 * @interface GenerateTitleResponse
 */
export interface GenerateTitleResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerateTitleResponse
     */
    title: string;
}

/**
 * Check if a given object implements the GenerateTitleResponse interface.
 */
export function instanceOfGenerateTitleResponse(value: object): value is GenerateTitleResponse {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function GenerateTitleResponseFromJSON(json: any): GenerateTitleResponse {
    return GenerateTitleResponseFromJSONTyped(json, false);
}

export function GenerateTitleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateTitleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function GenerateTitleResponseToJSON(json: any): GenerateTitleResponse {
    return GenerateTitleResponseToJSONTyped(json, false);
}

export function GenerateTitleResponseToJSONTyped(value?: GenerateTitleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
    };
}

