/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Generate title request.
 * 
 * Parameters are optional - if not provided, the backend will read
 * from wire.jsonl automatically.
 * @export
 * @interface GenerateTitleRequest
 */
export interface GenerateTitleRequest {
    /**
     * 
     * @type {string}
     * @memberof GenerateTitleRequest
     */
    userMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GenerateTitleRequest
     */
    assistantResponse?: string | null;
}

/**
 * Check if a given object implements the GenerateTitleRequest interface.
 */
export function instanceOfGenerateTitleRequest(value: object): value is GenerateTitleRequest {
    return true;
}

export function GenerateTitleRequestFromJSON(json: any): GenerateTitleRequest {
    return GenerateTitleRequestFromJSONTyped(json, false);
}

export function GenerateTitleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateTitleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userMessage': json['user_message'] == null ? undefined : json['user_message'],
        'assistantResponse': json['assistant_response'] == null ? undefined : json['assistant_response'],
    };
}

export function GenerateTitleRequestToJSON(json: any): GenerateTitleRequest {
    return GenerateTitleRequestToJSONTyped(json, false);
}

export function GenerateTitleRequestToJSONTyped(value?: GenerateTitleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_message': value['userMessage'],
        'assistant_response': value['assistantResponse'],
    };
}

