/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GitFileDiff } from './GitFileDiff';
import {
    GitFileDiffFromJSON,
    GitFileDiffFromJSONTyped,
    GitFileDiffToJSON,
    GitFileDiffToJSONTyped,
} from './GitFileDiff';

/**
 * Git diff statistics for a work directory.
 * @export
 * @interface GitDiffStats
 */
export interface GitDiffStats {
    /**
     * Whether the directory is a git repo
     * @type {boolean}
     * @memberof GitDiffStats
     */
    isGitRepo: boolean;
    /**
     * Whether there are uncommitted changes
     * @type {boolean}
     * @memberof GitDiffStats
     */
    hasChanges?: boolean;
    /**
     * Total added lines
     * @type {number}
     * @memberof GitDiffStats
     */
    totalAdditions?: number;
    /**
     * Total deleted lines
     * @type {number}
     * @memberof GitDiffStats
     */
    totalDeletions?: number;
    /**
     * Per-file diff stats
     * @type {Array<GitFileDiff>}
     * @memberof GitDiffStats
     */
    files?: Array<GitFileDiff>;
    /**
     * 
     * @type {string}
     * @memberof GitDiffStats
     */
    error?: string | null;
}

/**
 * Check if a given object implements the GitDiffStats interface.
 */
export function instanceOfGitDiffStats(value: object): value is GitDiffStats {
    if (!('isGitRepo' in value) || value['isGitRepo'] === undefined) return false;
    return true;
}

export function GitDiffStatsFromJSON(json: any): GitDiffStats {
    return GitDiffStatsFromJSONTyped(json, false);
}

export function GitDiffStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitDiffStats {
    if (json == null) {
        return json;
    }
    return {
        
        'isGitRepo': json['is_git_repo'],
        'hasChanges': json['has_changes'] == null ? undefined : json['has_changes'],
        'totalAdditions': json['total_additions'] == null ? undefined : json['total_additions'],
        'totalDeletions': json['total_deletions'] == null ? undefined : json['total_deletions'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(GitFileDiffFromJSON)),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GitDiffStatsToJSON(json: any): GitDiffStats {
    return GitDiffStatsToJSONTyped(json, false);
}

export function GitDiffStatsToJSONTyped(value?: GitDiffStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_git_repo': value['isGitRepo'],
        'has_changes': value['hasChanges'],
        'total_additions': value['totalAdditions'],
        'total_deletions': value['totalDeletions'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(GitFileDiffToJSON)),
        'error': value['error'],
    };
}

