/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Single file git diff statistics
 * @export
 * @interface GitFileDiff
 */
export interface GitFileDiff {
    /**
     * File path
     * @type {string}
     * @memberof GitFileDiff
     */
    path: string;
    /**
     * Number of added lines
     * @type {number}
     * @memberof GitFileDiff
     */
    additions: number;
    /**
     * Number of deleted lines
     * @type {number}
     * @memberof GitFileDiff
     */
    deletions: number;
    /**
     * File change status
     * @type {string}
     * @memberof GitFileDiff
     */
    status: GitFileDiffStatusEnum;
}


/**
 * @export
 */
export const GitFileDiffStatusEnum = {
    Added: 'added',
    Modified: 'modified',
    Deleted: 'deleted',
    Renamed: 'renamed'
} as const;
export type GitFileDiffStatusEnum = typeof GitFileDiffStatusEnum[keyof typeof GitFileDiffStatusEnum];


/**
 * Check if a given object implements the GitFileDiff interface.
 */
export function instanceOfGitFileDiff(value: object): value is GitFileDiff {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('additions' in value) || value['additions'] === undefined) return false;
    if (!('deletions' in value) || value['deletions'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GitFileDiffFromJSON(json: any): GitFileDiff {
    return GitFileDiffFromJSONTyped(json, false);
}

export function GitFileDiffFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitFileDiff {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'additions': json['additions'],
        'deletions': json['deletions'],
        'status': json['status'],
    };
}

export function GitFileDiffToJSON(json: any): GitFileDiff {
    return GitFileDiffToJSONTyped(json, false);
}

export function GitFileDiffToJSONTyped(value?: GitFileDiff | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'additions': value['additions'],
        'deletions': value['deletions'],
        'status': value['status'],
    };
}

