/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ModelCapability = {
    ImageIn: 'image_in',
    VideoIn: 'video_in',
    Thinking: 'thinking',
    AlwaysThinking: 'always_thinking'
} as const;
export type ModelCapability = typeof ModelCapability[keyof typeof ModelCapability];


export function instanceOfModelCapability(value: any): boolean {
    for (const key in ModelCapability) {
        if (Object.prototype.hasOwnProperty.call(ModelCapability, key)) {
            if (ModelCapability[key as keyof typeof ModelCapability] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ModelCapabilityFromJSON(json: any): ModelCapability {
    return ModelCapabilityFromJSONTyped(json, false);
}

export function ModelCapabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelCapability {
    return json as ModelCapability;
}

export function ModelCapabilityToJSON(value?: ModelCapability | null): any {
    return value as any;
}

export function ModelCapabilityToJSONTyped(value: any, ignoreDiscriminator: boolean): ModelCapability {
    return value as ModelCapability;
}

