/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Open path in a local app.
 * @export
 * @interface OpenInRequest
 */
export interface OpenInRequest {
    /**
     * 
     * @type {string}
     * @memberof OpenInRequest
     */
    app: OpenInRequestAppEnum;
    /**
     * 
     * @type {string}
     * @memberof OpenInRequest
     */
    path: string;
}


/**
 * @export
 */
export const OpenInRequestAppEnum = {
    Finder: 'finder',
    Cursor: 'cursor',
    Vscode: 'vscode',
    Iterm: 'iterm',
    Terminal: 'terminal',
    Antigravity: 'antigravity'
} as const;
export type OpenInRequestAppEnum = typeof OpenInRequestAppEnum[keyof typeof OpenInRequestAppEnum];


/**
 * Check if a given object implements the OpenInRequest interface.
 */
export function instanceOfOpenInRequest(value: object): value is OpenInRequest {
    if (!('app' in value) || value['app'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function OpenInRequestFromJSON(json: any): OpenInRequest {
    return OpenInRequestFromJSONTyped(json, false);
}

export function OpenInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'],
        'path': json['path'],
    };
}

export function OpenInRequestToJSON(json: any): OpenInRequest {
    return OpenInRequestToJSONTyped(json, false);
}

export function OpenInRequestToJSONTyped(value?: OpenInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
        'path': value['path'],
    };
}

