/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Open path response.
 * @export
 * @interface OpenInResponse
 */
export interface OpenInResponse {
    /**
     * 
     * @type {boolean}
     * @memberof OpenInResponse
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof OpenInResponse
     */
    detail?: string | null;
}

/**
 * Check if a given object implements the OpenInResponse interface.
 */
export function instanceOfOpenInResponse(value: object): value is OpenInResponse {
    if (!('ok' in value) || value['ok'] === undefined) return false;
    return true;
}

export function OpenInResponseFromJSON(json: any): OpenInResponse {
    return OpenInResponseFromJSONTyped(json, false);
}

export function OpenInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function OpenInResponseToJSON(json: any): OpenInResponse {
    return OpenInResponseToJSONTyped(json, false);
}

export function OpenInResponseToJSONTyped(value?: OpenInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
        'detail': value['detail'],
    };
}

