/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SessionStatus } from './SessionStatus';
import {
    SessionStatusFromJSON,
    SessionStatusFromJSONTyped,
    SessionStatusToJSON,
    SessionStatusToJSONTyped,
} from './SessionStatus';

/**
 * Web UI session metadata.
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * Session unique ID
     * @type {string}
     * @memberof Session
     */
    sessionId: string;
    /**
     * Session title derived from kimi-cli history
     * @type {string}
     * @memberof Session
     */
    title: string;
    /**
     * Last updated timestamp
     * @type {Date}
     * @memberof Session
     */
    lastUpdated: Date;
    /**
     * Whether the session is running
     * @type {boolean}
     * @memberof Session
     */
    isRunning?: boolean;
    /**
     * 
     * @type {SessionStatus}
     * @memberof Session
     */
    status?: SessionStatus | null;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    workDir?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    sessionDir?: string | null;
    /**
     * Whether the session is archived
     * @type {boolean}
     * @memberof Session
     */
    archived?: boolean;
}

/**
 * Check if a given object implements the Session interface.
 */
export function instanceOfSession(value: object): value is Session {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('lastUpdated' in value) || value['lastUpdated'] === undefined) return false;
    return true;
}

export function SessionFromJSON(json: any): Session {
    return SessionFromJSONTyped(json, false);
}

export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['session_id'],
        'title': json['title'],
        'lastUpdated': (new Date(json['last_updated'])),
        'isRunning': json['is_running'] == null ? undefined : json['is_running'],
        'status': json['status'] == null ? undefined : SessionStatusFromJSON(json['status']),
        'workDir': json['work_dir'] == null ? undefined : json['work_dir'],
        'sessionDir': json['session_dir'] == null ? undefined : json['session_dir'],
        'archived': json['archived'] == null ? undefined : json['archived'],
    };
}

export function SessionToJSON(json: any): Session {
    return SessionToJSONTyped(json, false);
}

export function SessionToJSONTyped(value?: Session | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'session_id': value['sessionId'],
        'title': value['title'],
        'last_updated': value['lastUpdated'].toISOString(),
        'is_running': value['isRunning'],
        'status': SessionStatusToJSON(value['status']),
        'work_dir': value['workDir'],
        'session_dir': value['sessionDir'],
        'archived': value['archived'],
    };
}

