/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to update global config.
 * @export
 * @interface UpdateGlobalConfigRequest
 */
export interface UpdateGlobalConfigRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateGlobalConfigRequest
     */
    defaultModel?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGlobalConfigRequest
     */
    defaultThinking?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGlobalConfigRequest
     */
    restartRunningSessions?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateGlobalConfigRequest
     */
    forceRestartBusySessions?: boolean | null;
}

/**
 * Check if a given object implements the UpdateGlobalConfigRequest interface.
 */
export function instanceOfUpdateGlobalConfigRequest(value: object): value is UpdateGlobalConfigRequest {
    return true;
}

export function UpdateGlobalConfigRequestFromJSON(json: any): UpdateGlobalConfigRequest {
    return UpdateGlobalConfigRequestFromJSONTyped(json, false);
}

export function UpdateGlobalConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGlobalConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultModel': json['default_model'] == null ? undefined : json['default_model'],
        'defaultThinking': json['default_thinking'] == null ? undefined : json['default_thinking'],
        'restartRunningSessions': json['restart_running_sessions'] == null ? undefined : json['restart_running_sessions'],
        'forceRestartBusySessions': json['force_restart_busy_sessions'] == null ? undefined : json['force_restart_busy_sessions'],
    };
}

export function UpdateGlobalConfigRequestToJSON(json: any): UpdateGlobalConfigRequest {
    return UpdateGlobalConfigRequestToJSONTyped(json, false);
}

export function UpdateGlobalConfigRequestToJSONTyped(value?: UpdateGlobalConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'default_model': value['defaultModel'],
        'default_thinking': value['defaultThinking'],
        'restart_running_sessions': value['restartRunningSessions'],
        'force_restart_busy_sessions': value['forceRestartBusySessions'],
    };
}

