/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GlobalConfig } from './GlobalConfig';
import {
    GlobalConfigFromJSON,
    GlobalConfigFromJSONTyped,
    GlobalConfigToJSON,
    GlobalConfigToJSONTyped,
} from './GlobalConfig';

/**
 * Response after updating global config.
 * @export
 * @interface UpdateGlobalConfigResponse
 */
export interface UpdateGlobalConfigResponse {
    /**
     * Updated config snapshot
     * @type {GlobalConfig}
     * @memberof UpdateGlobalConfigResponse
     */
    config: GlobalConfig;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateGlobalConfigResponse
     */
    restartedSessionIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateGlobalConfigResponse
     */
    skippedBusySessionIds?: Array<string> | null;
}

/**
 * Check if a given object implements the UpdateGlobalConfigResponse interface.
 */
export function instanceOfUpdateGlobalConfigResponse(value: object): value is UpdateGlobalConfigResponse {
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function UpdateGlobalConfigResponseFromJSON(json: any): UpdateGlobalConfigResponse {
    return UpdateGlobalConfigResponseFromJSONTyped(json, false);
}

export function UpdateGlobalConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGlobalConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'config': GlobalConfigFromJSON(json['config']),
        'restartedSessionIds': json['restarted_session_ids'] == null ? undefined : json['restarted_session_ids'],
        'skippedBusySessionIds': json['skipped_busy_session_ids'] == null ? undefined : json['skipped_busy_session_ids'],
    };
}

export function UpdateGlobalConfigResponseToJSON(json: any): UpdateGlobalConfigResponse {
    return UpdateGlobalConfigResponseToJSONTyped(json, false);
}

export function UpdateGlobalConfigResponseToJSONTyped(value?: UpdateGlobalConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'config': GlobalConfigToJSON(value['config']),
        'restarted_session_ids': value['restartedSessionIds'],
        'skipped_busy_session_ids': value['skippedBusySessionIds'],
    };
}

