/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to update config.toml.
 * @export
 * @interface UpdateConfigTomlRequest
 */
export interface UpdateConfigTomlRequest {
    /**
     * New TOML content
     * @type {string}
     * @memberof UpdateConfigTomlRequest
     */
    content: string;
}

/**
 * Check if a given object implements the UpdateConfigTomlRequest interface.
 */
export function instanceOfUpdateConfigTomlRequest(value: object): value is UpdateConfigTomlRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function UpdateConfigTomlRequestFromJSON(json: any): UpdateConfigTomlRequest {
    return UpdateConfigTomlRequestFromJSONTyped(json, false);
}

export function UpdateConfigTomlRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConfigTomlRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function UpdateConfigTomlRequestToJSON(json: any): UpdateConfigTomlRequest {
    return UpdateConfigTomlRequestToJSONTyped(json, false);
}

export function UpdateConfigTomlRequestToJSONTyped(value?: UpdateConfigTomlRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

