/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Update session request.
 * @export
 * @interface UpdateSessionRequest
 */
export interface UpdateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateSessionRequest
     */
    title?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSessionRequest
     */
    archived?: boolean | null;
}

/**
 * Check if a given object implements the UpdateSessionRequest interface.
 */
export function instanceOfUpdateSessionRequest(value: object): value is UpdateSessionRequest {
    return true;
}

export function UpdateSessionRequestFromJSON(json: any): UpdateSessionRequest {
    return UpdateSessionRequestFromJSONTyped(json, false);
}

export function UpdateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'archived': json['archived'] == null ? undefined : json['archived'],
    };
}

export function UpdateSessionRequestToJSON(json: any): UpdateSessionRequest {
    return UpdateSessionRequestToJSONTyped(json, false);
}

export function UpdateSessionRequestToJSONTyped(value?: UpdateSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'archived': value['archived'],
    };
}

