/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response after updating config.toml.
 * @export
 * @interface UpdateConfigTomlResponse
 */
export interface UpdateConfigTomlResponse {
    /**
     * Whether the update was successful
     * @type {boolean}
     * @memberof UpdateConfigTomlResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateConfigTomlResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the UpdateConfigTomlResponse interface.
 */
export function instanceOfUpdateConfigTomlResponse(value: object): value is UpdateConfigTomlResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UpdateConfigTomlResponseFromJSON(json: any): UpdateConfigTomlResponse {
    return UpdateConfigTomlResponseFromJSONTyped(json, false);
}

export function UpdateConfigTomlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateConfigTomlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function UpdateConfigTomlResponseToJSON(json: any): UpdateConfigTomlResponse {
    return UpdateConfigTomlResponseToJSONTyped(json, false);
}

export function UpdateConfigTomlResponseToJSONTyped(value?: UpdateConfigTomlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
    };
}

