/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Upload file response.
 * @export
 * @interface UploadSessionFileResponse
 */
export interface UploadSessionFileResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadSessionFileResponse
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof UploadSessionFileResponse
     */
    filename: string;
    /**
     * 
     * @type {number}
     * @memberof UploadSessionFileResponse
     */
    size: number;
}

/**
 * Check if a given object implements the UploadSessionFileResponse interface.
 */
export function instanceOfUploadSessionFileResponse(value: object): value is UploadSessionFileResponse {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function UploadSessionFileResponseFromJSON(json: any): UploadSessionFileResponse {
    return UploadSessionFileResponseFromJSONTyped(json, false);
}

export function UploadSessionFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadSessionFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
        'filename': json['filename'],
        'size': json['size'],
    };
}

export function UploadSessionFileResponseToJSON(json: any): UploadSessionFileResponse {
    return UploadSessionFileResponseToJSONTyped(json, false);
}

export function UploadSessionFileResponseToJSONTyped(value?: UploadSessionFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
        'filename': value['filename'],
        'size': value['size'],
    };
}

