/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  OpenInRequest,
  OpenInResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    OpenInRequestFromJSON,
    OpenInRequestToJSON,
    OpenInResponseFromJSON,
    OpenInResponseToJSON,
} from '../models/index';

export interface OpenInApiOpenInPostRequest {
    openInRequest: OpenInRequest;
}

/**
 * 
 */
export class OpenInApi extends runtime.BaseAPI {

    /**
     * Open a path in a local application
     */
    async openInApiOpenInPostRaw(requestParameters: OpenInApiOpenInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OpenInResponse>> {
        if (requestParameters['openInRequest'] == null) {
            throw new runtime.RequiredError(
                'openInRequest',
                'Required parameter "openInRequest" was null or undefined when calling openInApiOpenInPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/open-in`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OpenInRequestToJSON(requestParameters['openInRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OpenInResponseFromJSON(jsonValue));
    }

    /**
     * Open a path in a local application
     */
    async openInApiOpenInPost(requestParameters: OpenInApiOpenInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OpenInResponse> {
        const response = await this.openInApiOpenInPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
