/* tslint:disable */
/* eslint-disable */
/**
 * Kimi Code CLI Web Interface
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSessionRequest,
  GenerateTitleRequest,
  GenerateTitleResponse,
  GitDiffStats,
  HTTPValidationError,
  Session,
  UpdateSessionRequest,
  UploadSessionFileResponse,
} from '../models/index';
import {
    CreateSessionRequestFromJSON,
    CreateSessionRequestToJSON,
    GenerateTitleRequestFromJSON,
    GenerateTitleRequestToJSON,
    GenerateTitleResponseFromJSON,
    GenerateTitleResponseToJSON,
    GitDiffStatsFromJSON,
    GitDiffStatsToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SessionFromJSON,
    SessionToJSON,
    UpdateSessionRequestFromJSON,
    UpdateSessionRequestToJSON,
    UploadSessionFileResponseFromJSON,
    UploadSessionFileResponseToJSON,
} from '../models/index';

export interface CreateSessionApiSessionsPostRequest {
    createSessionRequest?: CreateSessionRequest;
}

export interface DeleteSessionApiSessionsSessionIdDeleteRequest {
    sessionId: string;
}

export interface GenerateSessionTitleApiSessionsSessionIdGenerateTitlePostRequest {
    sessionId: string;
    generateTitleRequest?: GenerateTitleRequest;
}

export interface GetSessionApiSessionsSessionIdGetRequest {
    sessionId: string;
}

export interface GetSessionFileApiSessionsSessionIdFilesPathGetRequest {
    sessionId: string;
    path: string;
}

export interface GetSessionGitDiffApiSessionsSessionIdGitDiffGetRequest {
    sessionId: string;
}

export interface GetSessionUploadFileApiSessionsSessionIdUploadsPathGetRequest {
    sessionId: string;
    path: string;
}

export interface ListSessionsApiSessionsGetRequest {
    limit?: number;
    offset?: number;
    q?: string | null;
    archived?: boolean | null;
}

export interface UpdateSessionApiSessionsSessionIdPatchRequest {
    sessionId: string;
    updateSessionRequest: UpdateSessionRequest;
}

export interface UploadSessionFileApiSessionsSessionIdFilesPostRequest {
    sessionId: string;
    file: Blob;
}

/**
 * 
 */
export class SessionsApi extends runtime.BaseAPI {

    /**
     * Create a new session.
     * Create a new session
     */
    async createSessionApiSessionsPostRaw(requestParameters: CreateSessionApiSessionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sessions/`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSessionRequestToJSON(requestParameters['createSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Create a new session.
     * Create a new session
     */
    async createSessionApiSessionsPost(requestParameters: CreateSessionApiSessionsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.createSessionApiSessionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a session.
     * Delete a session
     */
    async deleteSessionApiSessionsSessionIdDeleteRaw(requestParameters: DeleteSessionApiSessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling deleteSessionApiSessionsSessionIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Delete a session.
     * Delete a session
     */
    async deleteSessionApiSessionsSessionIdDelete(requestParameters: DeleteSessionApiSessionsSessionIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.deleteSessionApiSessionsSessionIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate a concise session title using AI based on the first conversation turn.  If request body is empty or parameters are missing, the backend will automatically read the first turn from wire.jsonl.
     * Generate session title using AI
     */
    async generateSessionTitleApiSessionsSessionIdGenerateTitlePostRaw(requestParameters: GenerateSessionTitleApiSessionsSessionIdGenerateTitlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateTitleResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling generateSessionTitleApiSessionsSessionIdGenerateTitlePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sessions/{session_id}/generate-title`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateTitleRequestToJSON(requestParameters['generateTitleRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateTitleResponseFromJSON(jsonValue));
    }

    /**
     * Generate a concise session title using AI based on the first conversation turn.  If request body is empty or parameters are missing, the backend will automatically read the first turn from wire.jsonl.
     * Generate session title using AI
     */
    async generateSessionTitleApiSessionsSessionIdGenerateTitlePost(requestParameters: GenerateSessionTitleApiSessionsSessionIdGenerateTitlePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateTitleResponse> {
        const response = await this.generateSessionTitleApiSessionsSessionIdGenerateTitlePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a session by ID.
     * Get session
     */
    async getSessionApiSessionsSessionIdGetRaw(requestParameters: GetSessionApiSessionsSessionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionApiSessionsSessionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Get a session by ID.
     * Get session
     */
    async getSessionApiSessionsSessionIdGet(requestParameters: GetSessionApiSessionsSessionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.getSessionApiSessionsSessionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a file or list directory from session work directory.
     * Get file or list directory from session work_dir
     */
    async getSessionFileApiSessionsSessionIdFilesPathGetRaw(requestParameters: GetSessionFileApiSessionsSessionIdFilesPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionFileApiSessionsSessionIdFilesPathGet().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getSessionFileApiSessionsSessionIdFilesPathGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/files/{path}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get a file or list directory from session work directory.
     * Get file or list directory from session work_dir
     */
    async getSessionFileApiSessionsSessionIdFilesPathGet(requestParameters: GetSessionFileApiSessionsSessionIdFilesPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSessionFileApiSessionsSessionIdFilesPathGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get git diff stats for the session\'s work directory
     * Get git diff stats
     */
    async getSessionGitDiffApiSessionsSessionIdGitDiffGetRaw(requestParameters: GetSessionGitDiffApiSessionsSessionIdGitDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GitDiffStats>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionGitDiffApiSessionsSessionIdGitDiffGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/git-diff`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GitDiffStatsFromJSON(jsonValue));
    }

    /**
     * get git diff stats for the session\'s work directory
     * Get git diff stats
     */
    async getSessionGitDiffApiSessionsSessionIdGitDiffGet(requestParameters: GetSessionGitDiffApiSessionsSessionIdGitDiffGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GitDiffStats> {
        const response = await this.getSessionGitDiffApiSessionsSessionIdGitDiffGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a file from a session\'s uploads directory.
     * Get uploaded file from session uploads
     */
    async getSessionUploadFileApiSessionsSessionIdUploadsPathGetRaw(requestParameters: GetSessionUploadFileApiSessionsSessionIdUploadsPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling getSessionUploadFileApiSessionsSessionIdUploadsPathGet().'
            );
        }

        if (requestParameters['path'] == null) {
            throw new runtime.RequiredError(
                'path',
                'Required parameter "path" was null or undefined when calling getSessionUploadFileApiSessionsSessionIdUploadsPathGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/{session_id}/uploads/{path}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));
        urlPath = urlPath.replace(`{${"path"}}`, encodeURIComponent(String(requestParameters['path'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get a file from a session\'s uploads directory.
     * Get uploaded file from session uploads
     */
    async getSessionUploadFileApiSessionsSessionIdUploadsPathGet(requestParameters: GetSessionUploadFileApiSessionsSessionIdUploadsPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSessionUploadFileApiSessionsSessionIdUploadsPathGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List sessions with optional pagination and search.  Args:     limit: Maximum number of sessions to return (default 100, max 500).     offset: Number of sessions to skip (default 0).     q: Optional search query to filter by title or work_dir.     archived: Filter by archived status.         - None (default): Only return non-archived sessions.         - True: Only return archived sessions.
     * List all sessions
     */
    async listSessionsApiSessionsGetRaw(requestParameters: ListSessionsApiSessionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Session>>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['archived'] != null) {
            queryParameters['archived'] = requestParameters['archived'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/sessions/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionFromJSON));
    }

    /**
     * List sessions with optional pagination and search.  Args:     limit: Maximum number of sessions to return (default 100, max 500).     offset: Number of sessions to skip (default 0).     q: Optional search query to filter by title or work_dir.     archived: Filter by archived status.         - None (default): Only return non-archived sessions.         - True: Only return archived sessions.
     * List all sessions
     */
    async listSessionsApiSessionsGet(requestParameters: ListSessionsApiSessionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Session>> {
        const response = await this.listSessionsApiSessionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a session (e.g., rename title or archive/unarchive).
     * Update session
     */
    async updateSessionApiSessionsSessionIdPatchRaw(requestParameters: UpdateSessionApiSessionsSessionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Session>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling updateSessionApiSessionsSessionIdPatch().'
            );
        }

        if (requestParameters['updateSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateSessionRequest',
                'Required parameter "updateSessionRequest" was null or undefined when calling updateSessionApiSessionsSessionIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/sessions/{session_id}`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSessionRequestToJSON(requestParameters['updateSessionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     * Update a session (e.g., rename title or archive/unarchive).
     * Update session
     */
    async updateSessionApiSessionsSessionIdPatch(requestParameters: UpdateSessionApiSessionsSessionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Session> {
        const response = await this.updateSessionApiSessionsSessionIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a file to a session.
     * Upload file to session
     */
    async uploadSessionFileApiSessionsSessionIdFilesPostRaw(requestParameters: UploadSessionFileApiSessionsSessionIdFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadSessionFileResponse>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling uploadSessionFileApiSessionsSessionIdFilesPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadSessionFileApiSessionsSessionIdFilesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/sessions/{session_id}/files`;
        urlPath = urlPath.replace(`{${"session_id"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadSessionFileResponseFromJSON(jsonValue));
    }

    /**
     * Upload a file to a session.
     * Upload file to session
     */
    async uploadSessionFileApiSessionsSessionIdFilesPost(requestParameters: UploadSessionFileApiSessionsSessionIdFilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadSessionFileResponse> {
        const response = await this.uploadSessionFileApiSessionsSessionIdFilesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
